### ISSUE TITLE
Can’t uninstall or update, can’t bootstrap

### ISSUE THREAD

**Issue by Manchovies** [Stillrem/Bootstrap-Beta#25]
You have installed an old beta version, please disable all app tweaks and reboot the device to uninstall it so that you can install the new version bootstrap.

I have tried to install the older beta versions listed here with no luck. Same error. I’ve rebooted but when I go to uninstall, it tells me I should disable all apps in the app enabler but I can’t do that because I’m not bootstrapped, and it won’t let me. I’ve tried the old beta IPA files listed here and I have the same issue with all of them, and I can’t find any older beta IPA files that look like the one I used. How can I uninstall safely so I can update to the new version?

**Comment by Stillrem** [comment]
You need to install Bootstrap first and only then you can disable all enabled apps in app enabler and only then you can uninstall.

**Comment by Manchovies** [comment]
I had Bootstrap installed. I tried all versions of the app I could find and none of them let me bootstrap so that I could disable the apps. I ended up taking a chance and uninstalled the bootstrap I had installed and installed the official 1.0 IPA and re-installed it.

**Comment by Stillrem** [comment]
Everything's fine now👍
